title: "Kristina Morreale Personal Website"
profile_img: "/assets/img/image.png"
icon_img: "/assets/img/icon.webp"

name: "Kristina Morreale"
job: "Clinical Research Coordinator III"
current_affiliations: "UMass Medical School & Regis College"

contents:
  - title: "About Me"
    description: >
      I am a researcher interested in cognitive functioning and neural mechanisms, particularly in individuals with head injuries or emotional memory impairments. 
      I have experience studying cognition in individuals across the lifespan, including those with complicated head injury histories. 
      I look forward to, one day, continuing my education in a PhD program.

email: "Kmorr10@unh.newhaven.edu"
linkedin_username: "https://www.linkedin.com/in/kristina-morreale-research/"
youtube_username: "https://youtu.be/97CphAGynGg"
cv_link: "https://github.com/Kristina.Research/Kristina.Research.github.io/raw/main/Morreale%20CV%202025.pdf"

# If your repo name follows the format "<user-name>.github.io", leave blank.
# Otherwise, set its value as "/<repo-name>"
baseurl: ""

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

